cora_independent_node:
  version: independent
  dataset: cora
  node_classification: True
  pretrain_epochs: 500
  finetune_epochs: 500
  finetune_interval: 50
  pretrain_lr: 0.001
  finetune_lr: 0.001
  pretrain_wd: 5e-4
  finetune_wd: 0
  pretrain_dropout: 0.1
  finetune_dropout: 0.9
  encoder_type: gcn
  encoder_layers: 2
  decoder_type: gcn
  decoder_layers: 2
  attr_loss_type: bce
  num_hidden: 512
  out_dim: 512
  aug_e: 0
  aug_a: 0
  eps: 1e-10

cora_correlated_node:
  version: correlated
  dataset: cora
  node_classification: True
  pretrain_epochs: 500
  finetune_epochs: 500
  finetune_interval: 50
  pretrain_lr: 0.001
  finetune_lr: 0.001
  pretrain_wd: 0.001
  finetune_wd: 0.001
  pretrain_dropout: 0.3
  finetune_dropout: 0.9
  encoder_type: gcn
  encoder_layers: 2
  decoder_type: gcn
  decoder_layers: 2
  attr_loss_type: bce
  num_hidden: 512
  out_dim: 512
  aug_e: 0
  aug_a: 0
  eps: 1e-10

cora_correlated_masking_node:
  version: correlated
  dataset: cora
  node_classification: True
  pretrain_epochs: 500
  finetune_epochs: 500
  finetune_interval: 50
  pretrain_lr: 0.001
  finetune_lr: 0.001
  pretrain_wd: 0.001
  finetune_wd: 0.001
  pretrain_dropout: 0.3
  finetune_dropout: 0.9
  encoder_type: gcn
  encoder_layers: 2
  decoder_type: gcn
  decoder_layers: 2
  attr_loss_type: bce
  num_hidden: 512
  out_dim: 512
  aug_e: 0.2
  aug_a: 0.1
  eps: 1e-10

cora_independent_link:
  version: independent
  dataset: cora
  link_prediction: True
  pretrain_epochs: 3500
  finetune_epochs: 0
  finetune_interval: 0
  pretrain_lr: 0.001
  finetune_lr: 0.0
  pretrain_wd: 5e-5
  finetune_wd: 0
  pretrain_dropout: 0.1
  finetune_dropout: 0.0
  encoder_type: gcn
  encoder_layers: 1
  decoder_type: gcn
  decoder_layers: 1
  attr_loss_type: bce
  num_hidden: 512
  out_dim: 512
  aug_e: 0
  aug_a: 0
  eps: 1e-10

cora_correlated_link:
  version: correlated
  dataset: cora
  link_prediction: True
  pretrain_epochs: 3500
  finetune_epochs: 0
  finetune_interval: 0
  pretrain_lr: 0.001
  finetune_lr: 0.0
  pretrain_wd: 5e-5
  finetune_wd: 0
  pretrain_dropout: 0.3
  finetune_dropout: 0.0
  encoder_type: gcn
  encoder_layers: 2
  decoder_type: gcn
  decoder_layers: 3
  attr_loss_type: bce
  num_hidden: 512
  out_dim: 512
  aug_e: 0
  aug_a: 0
  eps: 1e-10

cora_correlated_masking_link:
  version: correlated
  dataset: cora
  link_prediction: True
  pretrain_epochs: 3500
  finetune_epochs: 0
  finetune_interval: 0
  pretrain_lr: 0.001
  finetune_lr: 0.0
  pretrain_wd: 5e-5
  finetune_wd: 0
  pretrain_dropout: 0.3
  finetune_dropout: 0.0
  encoder_type: gcn
  encoder_layers: 2
  decoder_type: gcn
  decoder_layers: 3
  attr_loss_type: bce
  num_hidden: 512
  out_dim: 512
  aug_e: 0.3
  aug_a: 0.0
  eps: 1e-10

cora_independent_attr:
  version: independent
  dataset: cora
  attr_inference: True
  pretrain_epochs: 3500
  finetune_epochs: 0
  finetune_interval: 0
  pretrain_lr: 0.001
  finetune_lr: 0.0
  pretrain_wd: 5e-5
  finetune_wd: 0.0
  pretrain_dropout: 0.1
  finetune_dropout: 0.0
  encoder_type: gcn
  encoder_layers: 1
  decoder_type: gcn
  decoder_layers: 1
  attr_loss_type: mse
  num_hidden: 512
  out_dim: 512
  aug_e: 0
  aug_a: 0
  eps: 1e-10

cora_correlated_attr:
  version: correlated
  dataset: cora
  attr_inference: True
  pretrain_epochs: 3500
  finetune_epochs: 0
  finetune_interval: 0
  pretrain_lr: 0.001
  finetune_lr: 0.0
  pretrain_wd: 5e-5
  finetune_wd: 0.0
  pretrain_dropout: 0.1
  finetune_dropout: 0.0
  encoder_type: gcn
  encoder_layers: 1
  decoder_type: gcn
  decoder_layers: 1
  attr_loss_type: mse
  num_hidden: 512
  out_dim: 512
  aug_e: 0
  aug_a: 0
  eps: 1e-10

cora_correlated_masking_attr:
  version: correlated
  dataset: cora
  attr_inference: True
  pretrain_epochs: 3500
  finetune_epochs: 0
  finetune_interval: 0
  pretrain_lr: 0.001
  finetune_lr: 0.0
  pretrain_wd: 5e-5
  finetune_wd: 0.0
  pretrain_dropout: 0.1
  finetune_dropout: 0.0
  encoder_type: gcn
  encoder_layers: 1
  decoder_type: gcn
  decoder_layers: 1
  attr_loss_type: mse
  num_hidden: 512
  out_dim: 512
  aug_e: 0.4
  aug_a: 0.0
  eps: 1e-10

citeseer_independent:
  version: independent
  dataset: citeseer
  node_classification: True
  pretrain_epochs: 500
  finetune_epochs: 500
  finetune_interval: 50
  pretrain_lr: 0.0005
  finetune_lr: 0.001
  pretrain_wd: 1e-3
  finetune_wd: 5e-4
  pretrain_dropout: 0.1
  finetune_dropout: 0.9
  encoder_type: gcn
  encoder_layers: 1
  decoder_type: gcn
  decoder_layers: 3
  attr_loss_type: bce
  num_hidden: 512
  out_dim: 512
  aug_e: 0
  aug_a: 0
  eps: 1e-8

citeseer_correlated_node:
  version: correlated
  dataset: citeseer
  node_classification: True
  pretrain_epochs: 500
  finetune_epochs: 500
  finetune_interval: 10
  pretrain_lr: 0.005
  finetune_lr: 0.001
  pretrain_wd: 5e-4
  finetune_wd: 0
  pretrain_dropout: 0.3
  finetune_dropout: 0.9
  encoder_type: gcn
  encoder_layers: 2
  decoder_type: gcn
  decoder_layers: 2
  attr_loss_type: bce
  num_hidden: 512
  out_dim: 512
  aug_e: 0
  aug_a: 0
  eps: 1e-8

citeseer_correlated_masking_node:
  version: correlated
  dataset: citeseer
  node_classification: True
  pretrain_epochs: 500
  finetune_epochs: 500
  finetune_interval: 10
  pretrain_lr: 0.005
  finetune_lr: 0.001
  pretrain_wd: 5e-4
  finetune_wd: 0
  pretrain_dropout: 0.3
  finetune_dropout: 0.9
  encoder_type: gcn
  encoder_layers: 2
  decoder_type: gcn
  decoder_layers: 2
  attr_loss_type: bce
  num_hidden: 512
  out_dim: 512
  aug_e: 0
  aug_a: 0
  eps: 1e-8

citeseer_independent_link:
  version: independent
  dataset: citeseer
  link_prediction: True
  pretrain_epochs: 3500
  finetune_epochs: 0
  finetune_interval: 0
  pretrain_lr: 0.001
  finetune_lr: 0.0
  pretrain_wd: 0
  finetune_wd: 0
  pretrain_dropout: 0.0
  finetune_dropout: 0.0
  encoder_type: gcn
  encoder_layers: 1
  decoder_type: gcn
  decoder_layers: 1
  attr_loss_type: bce
  num_hidden: 512
  out_dim: 512
  aug_e: 0.0
  aug_a: 0.0
  eps: 1e-8

citeseer_correlated_link:
  version: correlated
  dataset: citeseer
  link_prediction: True
  pretrain_epochs: 3500
  finetune_epochs: 0
  finetune_interval: 0
  pretrain_lr: 0.001
  finetune_lr: 0.0
  pretrain_wd: 1e-4
  finetune_wd: 0
  pretrain_dropout: 0.0
  finetune_dropout: 0.0
  encoder_type: gcn
  encoder_layers: 1
  decoder_type: gcn
  decoder_layers: 2
  attr_loss_type: bce
  num_hidden: 512
  out_dim: 512
  aug_e: 0.0
  aug_a: 0.0
  eps: 1e-8

citeseer_correlated_masking_link:
  version: correlated
  dataset: citeseer
  link_prediction: True
  pretrain_epochs: 3500
  finetune_epochs: 0
  finetune_interval: 0
  pretrain_lr: 0.001
  finetune_lr: 0.0
  pretrain_wd: 1e-4
  finetune_wd: 0
  pretrain_dropout: 0.0
  finetune_dropout: 0.0
  encoder_type: gcn
  encoder_layers: 1
  decoder_type: gcn
  decoder_layers: 2
  attr_loss_type: bce
  num_hidden: 512
  out_dim: 512
  aug_e: 0.6
  aug_a: 0.0
  eps: 1e-8

citeseer_independent_attr:
  version: independent
  dataset: citeseer
  link_prediction: True
  pretrain_epochs: 3500
  finetune_epochs: 0
  finetune_interval: 0
  pretrain_lr: 0.001
  finetune_lr: 0.0
  pretrain_wd: 0.0
  finetune_wd: 0
  pretrain_dropout: 0.0
  finetune_dropout: 0.0
  encoder_type: gcn
  encoder_layers: 1
  decoder_type: gcn
  decoder_layers: 1
  attr_loss_type: mse
  num_hidden: 512
  out_dim: 512
  aug_e: 0.0
  aug_a: 0.0
  eps: 1e-10

citeseer_correlated_attr:
  version: correlated
  dataset: citeseer
  link_prediction: True
  pretrain_epochs: 3500
  finetune_epochs: 0
  finetune_interval: 0
  pretrain_lr: 0.001
  finetune_lr: 0.0
  pretrain_wd: 0.0
  finetune_wd: 0
  pretrain_dropout: 0.0
  finetune_dropout: 0.0
  encoder_type: gcn
  encoder_layers: 1
  decoder_type: gcn
  decoder_layers: 1
  attr_loss_type: mse
  num_hidden: 512
  out_dim: 512
  aug_e: 0.0
  aug_a: 0.0
  eps: 1e-10

citeseer_correlated_masking_attr:
  version: correlated
  dataset: citeseer
  link_prediction: True
  pretrain_epochs: 3500
  finetune_epochs: 0
  finetune_interval: 0
  pretrain_lr: 0.001
  finetune_lr: 0.0
  pretrain_wd: 0.0
  finetune_wd: 0
  pretrain_dropout: 0.0
  finetune_dropout: 0.0
  encoder_type: gcn
  encoder_layers: 1
  decoder_type: gcn
  decoder_layers: 1
  attr_loss_type: mse
  num_hidden: 512
  out_dim: 512
  aug_e: 0.3
  aug_a: 0.0
  eps: 1e-10

pubmed_correlated_node:
  version: correlated
  dataset: pubmed
  node_classification: True
  pretrain_epochs: 1000
  finetune_epochs: 500
  finetune_interval: 10
  pretrain_lr: 0.0005
  finetune_lr: 0.001
  pretrain_wd: 0
  finetune_wd: 0
  pretrain_dropout: 0.7
  finetune_dropout: 0.3
  encoder_type: gcn
  encoder_layers: 2
  decoder_type: gcn
  decoder_layers: 1
  attr_loss_type: mse
  num_hidden: 1024
  out_dim: 1024
  aug_e: 0
  aug_a: 0
  eps: 1e-10

pubmed_correlated_masking_node:
  version: correlated
  dataset: pubmed
  node_classification: True
  pretrain_epochs: 1000
  finetune_epochs: 500
  finetune_interval: 10
  pretrain_lr: 0.0005
  finetune_lr: 0.001
  pretrain_wd: 0
  finetune_wd: 0
  pretrain_dropout: 0.7
  finetune_dropout: 0.3
  encoder_type: gcn
  encoder_layers: 2
  decoder_type: gcn
  decoder_layers: 1
  attr_loss_type: mse
  num_hidden: 1024
  out_dim: 1024
  aug_e: 0
  aug_a: 0
  eps: 1e-10

pubmed_correlated_masking_link:
  version: correlated
  dataset: pubmed
  link_prediction: True
  pretrain_epochs: 3500
  finetune_epochs: 0
  finetune_interval: 0
  pretrain_lr: 0.005
  finetune_lr: 0
  pretrain_wd: 0
  finetune_wd: 0
  pretrain_dropout: 0.5
  finetune_dropout: 0
  encoder_type: gcn
  encoder_layers: 2
  decoder_type: gcn
  decoder_layers: 1
  attr_loss_type: mse
  num_hidden: 512
  out_dim: 512
  aug_e: 0.3
  aug_a: 0.1
  eps: 1e-10

pubmed_correlated_masking_attr:
  version: correlated
  dataset: pubmed
  link_prediction: True
  pretrain_epochs: 3500
  finetune_epochs: 0
  finetune_interval: 0
  pretrain_lr: 0.001
  finetune_lr: 0
  pretrain_wd: 0
  finetune_wd: 0
  pretrain_dropout: 0
  finetune_dropout: 0
  encoder_type: gcn
  encoder_layers: 2
  decoder_type: gcn
  decoder_layers: 2
  attr_loss_type: mse
  num_hidden: 512
  out_dim: 512
  aug_e: 0.0
  aug_a: 0.1
  eps: 1e-10

cs_independent_node:
  version: independent
  dataset: cs
  node_classification: True
  pretrain_epochs: 20
  finetune_epochs: 500
  finetune_interval: 1
  pretrain_lr: 0.001
  finetune_lr: 0.001
  pretrain_wd: 0
  finetune_wd: 5e-4
  pretrain_dropout: 0.1
  finetune_dropout: 0.0
  encoder_type: gcn
  encoder_layers: 1
  decoder_type: gcn
  decoder_layers: 3
  attr_loss_type: mse
  num_hidden: 512
  out_dim: 512
  aug_e: 0
  aug_a: 0
  eps: 1e-10

cs_correlated_node:
  version: correlated
  dataset: cs
  node_classification: True
  pretrain_epochs: 40
  finetune_epochs: 500
  finetune_interval: 1
  pretrain_lr: 0.01
  finetune_lr: 0.01
  pretrain_wd: 1e-3
  finetune_wd: 1e-3
  pretrain_dropout: 0.1
  finetune_dropout: 0.0
  encoder_type: mlp
  encoder_layers: 2
  decoder_type: gcn
  decoder_layers: 3
  attr_loss_type: mse
  num_hidden: 512
  out_dim: 512
  aug_e: 0
  aug_a: 0
  eps: 1e-10

cs_correlated_masking_node:
  version: correlated
  dataset: cs
  node_classification: True
  pretrain_epochs: 40
  finetune_epochs: 500
  finetune_interval: 1
  pretrain_lr: 0.01
  finetune_lr: 0.01
  pretrain_wd: 1e-3
  finetune_wd: 1e-3
  pretrain_dropout: 0.1
  finetune_dropout: 0.0
  encoder_type: mlp
  encoder_layers: 2
  decoder_type: gcn
  decoder_layers: 3
  attr_loss_type: mse
  num_hidden: 512
  out_dim: 512
  aug_e: 0
  aug_a: 0
  eps: 1e-10

cs_correlated_masking_link:
  version: correlated
  dataset: cs
  link_prediction: True
  pretrain_epochs: 3500
  finetune_epochs: 0
  finetune_interval: 0
  pretrain_lr: 0.001
  finetune_lr: 0
  pretrain_wd: 0
  finetune_wd: 0
  pretrain_dropout: 0
  finetune_dropout: 0
  encoder_type: gcn
  encoder_layers: 1
  decoder_type: gcn
  decoder_layers: 2
  attr_loss_type: mse
  num_hidden: 512
  out_dim: 512
  aug_e: 0.5
  aug_a: 0.5
  eps: 1e-10

cs_correlated_masking_attr:
  version: correlated
  dataset: cs
  link_prediction: True
  pretrain_epochs: 3500
  finetune_epochs: 0
  finetune_interval: 0
  pretrain_lr: 0.001
  finetune_lr: 0
  pretrain_wd: 0
  finetune_wd: 0
  pretrain_dropout: 0
  finetune_dropout: 0
  encoder_type: gcn
  encoder_layers: 1
  decoder_type: gcn
  decoder_layers: 3
  attr_loss_type: mse
  num_hidden: 512
  out_dim: 512
  aug_e: 0.1
  aug_a: 0.5
  eps: 1e-10

physics_independent_node:
  version: independent
  dataset: physics
  node_classification: True
  pretrain_epochs: 50
  finetune_epochs: 500
  finetune_interval: 5
  pretrain_lr: 0.01
  finetune_lr: 0.005
  pretrain_wd: 0
  finetune_wd: 5e-4
  pretrain_dropout: 0.0
  finetune_dropout: 0.5
  encoder_type: gcn
  encoder_layers: 1
  decoder_type: gcn
  decoder_layers: 3
  attr_loss_type: mse
  num_hidden: 512
  out_dim: 512
  aug_e: 0
  aug_a: 0
  eps: 1e-10

physics_correlated_node:
  version: correlated
  dataset: physics
  node_classification: True
  pretrain_epochs: 50
  finetune_epochs: 500
  finetune_interval: 5
  pretrain_lr: 0.01
  finetune_lr: 0.01
  pretrain_wd: 0
  finetune_wd: 5e-5
  pretrain_dropout: 0.0
  finetune_dropout: 0.5
  encoder_type: gcn
  encoder_layers: 1
  decoder_type: gcn
  decoder_layers: 3
  attr_loss_type: mse
  num_hidden: 512
  out_dim: 512
  aug_e: 0
  aug_a: 0
  eps: 1e-10

physics_correlated_masking_node:
  version: correlated
  dataset: physics
  node_classification: True
  pretrain_epochs: 50
  finetune_epochs: 500
  finetune_interval: 5
  pretrain_lr: 0.01
  finetune_lr: 0.01
  pretrain_wd: 0
  finetune_wd: 5e-5
  pretrain_dropout: 0.0
  finetune_dropout: 0.5
  encoder_type: gcn
  encoder_layers: 1
  decoder_type: gcn
  decoder_layers: 3
  attr_loss_type: mse
  num_hidden: 512
  out_dim: 512
  aug_e: 0
  aug_a: 0
  eps: 1e-10

physics_correlated_masking_link:
  version: correlated
  dataset: physics
  link_prediction: True
  pretrain_epochs: 3500
  finetune_epochs: 0
  finetune_interval: 0
  pretrain_lr: 0.001
  finetune_lr: 0.0
  pretrain_wd: 0
  finetune_wd: 0
  pretrain_dropout: 0.0
  finetune_dropout: 0
  encoder_type: gcn
  encoder_layers: 2
  decoder_type: gcn
  decoder_layers: 2
  attr_loss_type: mse
  num_hidden: 512
  out_dim: 512
  aug_e: 0.2
  aug_a: 0
  eps: 1e-10

photo_independent_node:
  version: independent
  dataset: photo
  node_classification: True
  pretrain_epochs: 50
  finetune_epochs: 500
  finetune_interval: 2
  pretrain_lr: 0.001
  finetune_lr: 0.001
  pretrain_wd: 1e-4
  finetune_wd: 5e-5
  pretrain_dropout: 0.0
  finetune_dropout: 0.1
  encoder_type: gcn
  encoder_layers: 1
  decoder_type: gcn
  decoder_layers: 2
  attr_loss_type: mse
  num_hidden: 512
  out_dim: 512
  aug_e: 0
  aug_a: 0
  eps: 1e-10

photo_correlated_node:
  version: correlated
  dataset: photo
  node_classification: True
  pretrain_epochs: 50
  finetune_epochs: 500
  finetune_interval: 2
  pretrain_lr: 0.001
  finetune_lr: 0.005
  pretrain_wd: 5e-4
  finetune_wd: 5e-5
  pretrain_dropout: 0.0
  finetune_dropout: 0.7
  encoder_type: gcn
  encoder_layers: 1
  decoder_type: gcn
  decoder_layers: 2
  attr_loss_type: mse
  num_hidden: 512
  out_dim: 512
  aug_e: 0
  aug_a: 0
  eps: 1e-10

photo_correlated_masking_node:
  version: correlated
  dataset: photo
  node_classification: True
  pretrain_epochs: 50
  finetune_epochs: 500
  finetune_interval: 2
  pretrain_lr: 0.001
  finetune_lr: 0.005
  pretrain_wd: 5e-4
  finetune_wd: 5e-5
  pretrain_dropout: 0.0
  finetune_dropout: 0.7
  encoder_type: gcn
  encoder_layers: 1
  decoder_type: gcn
  decoder_layers: 2
  attr_loss_type: mse
  num_hidden: 512
  out_dim: 512
  aug_e: 0.5
  aug_a: 0.5
  eps: 1e-10

photo_independent_link:
  version: independent
  dataset: photo
  link_prediction: True
  pretrain_epochs: 3500
  finetune_epochs: 0
  finetune_interval: 0
  pretrain_lr: 0.001
  finetune_lr: 0.0
  pretrain_wd: 0.0
  finetune_wd: 0.0
  pretrain_dropout: 0.0
  finetune_dropout: 0.0
  encoder_type: gcn
  encoder_layers: 1
  decoder_type: gcn
  decoder_layers: 1
  attr_loss_type: mse
  num_hidden: 512
  out_dim: 512
  aug_e: 0
  aug_a: 0
  eps: 1e-10

photo_correlated_link:
  version: correlated
  dataset: photo
  link_prediction: True
  pretrain_epochs: 3500
  finetune_epochs: 0
  finetune_interval: 0
  pretrain_lr: 0.005
  finetune_lr: 0.0
  pretrain_wd: 0.0
  finetune_wd: 0.0
  pretrain_dropout: 0.0
  finetune_dropout: 0.0
  encoder_type: gcn
  encoder_layers: 1
  decoder_type: gcn
  decoder_layers: 1
  attr_loss_type: mse
  num_hidden: 512
  out_dim: 512
  aug_e: 0
  aug_a: 0
  eps: 1e-10

photo_correlated_masking_link:
  version: correlated
  dataset: photo
  link_prediction: True
  pretrain_epochs: 3500
  finetune_epochs: 0
  finetune_interval: 0
  pretrain_lr: 0.005
  finetune_lr: 0.0
  pretrain_wd: 0.0
  finetune_wd: 0.0
  pretrain_dropout: 0.0
  finetune_dropout: 0.0
  encoder_type: gcn
  encoder_layers: 1
  decoder_type: gcn
  decoder_layers: 1
  attr_loss_type: mse
  num_hidden: 512
  out_dim: 512
  aug_e: 0.5
  aug_a: 0
  eps: 1e-10

photo_correlated_masking_attr:
  version: correlated
  dataset: photo
  attr_inference: True
  pretrain_epochs: 3500
  finetune_epochs: 0
  finetune_interval: 0
  pretrain_lr: 0.001
  finetune_lr: 0.0
  pretrain_wd: 0.0
  finetune_wd: 0.0
  pretrain_dropout: 0.0
  finetune_dropout: 0.0
  encoder_type: gcn
  encoder_layers: 2
  decoder_type: gcn
  decoder_layers: 3
  attr_loss_type: mse
  num_hidden: 512
  out_dim: 512
  aug_e: 0.3
  aug_a: 0
  eps: 1e-10

comp_independent_node:
  version: independent
  dataset: comp
  node_classification: True
  pretrain_epochs: 100
  finetune_epochs: 500
  finetune_interval: 10
  pretrain_lr: 0.005
  finetune_lr: 0.01
  pretrain_wd: 5e-5
  finetune_wd: 0
  pretrain_dropout: 0.0
  finetune_dropout: 0.5
  encoder_type: gcn
  encoder_layers: 1
  decoder_type: gcn
  decoder_layers: 1
  attr_loss_type: mse
  num_hidden: 512
  out_dim: 512
  aug_e: 0
  aug_a: 0
  eps: 1e-10

comp_correlated_node:
  version: correlated
  dataset: comp
  node_classification: True
  pretrain_epochs: 100
  finetune_epochs: 500
  finetune_interval: 10
  pretrain_lr: 0.005
  finetune_lr: 0.005
  pretrain_wd: 5e-4
  finetune_wd: 1e-4
  pretrain_dropout: 0.0
  finetune_dropout: 0.3
  encoder_type: gcn
  encoder_layers: 1
  decoder_type: gcn
  decoder_layers: 3
  attr_loss_type: mse
  num_hidden: 512
  out_dim: 512
  aug_e: 0
  aug_a: 0
  eps: 1e-10

comp_correlated_masking_link:
  version: correlated
  dataset: comp
  link_prediction: True
  pretrain_epochs: 3500
  finetune_epochs: 0
  finetune_interval: 0
  pretrain_lr: 0.001
  finetune_lr: 0
  pretrain_wd: 0
  finetune_wd: 0
  pretrain_dropout: 0
  finetune_dropout: 0
  encoder_type: gcn
  encoder_layers: 2
  decoder_type: gcn
  decoder_layers: 2
  attr_loss_type: mse
  num_hidden: 512
  out_dim: 512
  aug_e: 0.4
  aug_a: 0
  eps: 1e-10

comp_correlated_masking_attr:
  version: correlated
  dataset: comp
  attr_inference: True
  pretrain_epochs: 3500
  finetune_epochs: 0
  finetune_interval: 0
  pretrain_lr: 0.001
  finetune_lr: 0
  pretrain_wd: 0
  finetune_wd: 0
  pretrain_dropout: 0
  finetune_dropout: 0
  encoder_type: gcn
  encoder_layers: 2
  decoder_type: gcn
  decoder_layers: 3
  attr_loss_type: mse
  num_hidden: 512
  out_dim: 512
  aug_e: 0.2
  aug_a: 0
  eps: 1e-10